import "./globals.css";

import { Providers } from "@/app/providers";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="bg-gradient-to-l from-red-400 to-orange-500 antialiased dark"
    >
      <body className="mx-auto max-w-screen-2xl ">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
