import "./globals.css";

import { Providers } from "@/app/providers";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className=" bg-gradient-to-r from-slate-500 to-stone-700 antialiased dark"
    >
      <body className="mx-auto h-full max-w-screen-2xl overflow-y-auto">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
